# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H58sbclgXX9Tow-T1a_fJJUz803ABvQW
"""

# Import libraries
import streamlit as st
import numpy as np
import joblib
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris

# Load model
model = joblib.load("iris_model.pkl")
iris = load_iris()

target_names = iris.target_names
feature_names = iris.feature_names
df = pd.DataFrame(iris.data, columns=feature_names)
df['target'] = iris.target

# Page title
st.title("Iris Flower Classifier")
st.markdown("Enter flower features below and the model will predict the species.")

# Input sliders
st.sidebar.header("Input Features")
sepal_length = st.sidebar.slider("Sepal length (cm)", 4.0, 8.0, 5.1)
sepal_width = st.sidebar.slider("Sepal width (cm)", 2.0, 4.5, 3.5)
petal_length = st.sidebar.slider("Petal length (cm)", 1.0, 7.0, 1.4)
petal_width = st.sidebar.slider("Petal width (cm)", 0.1, 2.5, 0.2)

input_data = np.array([[sepal_length, sepal_width, petal_length, petal_width]])

# Prediction
if st.button("Predict"):
    prediction = model.predict(input_data)[0]
    pred_prob = model.predict_proba(input_data)[0]
    st.success(f"Predicted Species: **{target_names[prediction]}**")
    st.write("Prediction Probabilities:")
    st.bar_chart(pred_prob)

# Visualization
st.subheader("🔍 Feature Distribution")
selected_feature = st.selectbox("Select a feature to visualize", feature_names)

fig, ax = plt.subplots()
sns.histplot(df[selected_feature], kde=True, bins=20, ax=ax)
st.pyplot(fig)
